### ISSUE TITLE
GitHub Actions are performed twice on the PR

### ISSUE THREAD

**Issue by jmesnil** [jbossas/eap-datasources-galleon-pack#13]
see https://github.com/jbossas/eap-datasources-galleon-pack/pull/11, we have:

* @github-actions EAP datasources and drivers Galleon feature-pack - CI / ubuntu-latest-jdk11 (pull_request) 
* @github-actions EAP datasources and drivers Galleon feature-pack - CI / ubuntu-latest-jdk11 (push)

I think we need to update the workflow file to only trigger it on:

```yaml
  push:
    branches:
      - main
```

**Comment by jfdenise** [comment]
I am wandering if we really need it on push to the main branch? On pull-request should be enough.

**Comment by jmesnil** [comment]
Running on main is fine. It ensures that what we deliver is properly tested and we have a CI status for the commit corresponding to any release.

it seems the issue was fixed in the latest checked PR https://github.com/jbossas/eap-datasources-galleon-pack/pull/16 (maybe it was a one-off when the project became public)...

Let's close this issue then.
